=== yoori/rtbserver_cobrazz/xsd/CampaignSvcs/DomainConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.adintelligence.net/xsd/AdServer/Configuration"
	    xmlns="http://www.adintelligence.net/xsd/AdServer/Configuration"
	    elementFormDefault="qualified"
	    xml:lang="en"
	    version="1.0">

  <xsd:annotation>
    <xsd:documentation>
      Top level domains Configuration File XML Schema
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="DomainConfiguration"
    type="DomainConfigurationType"/>

  <xsd:complexType name="DomainConfigurationType">
    <xsd:sequence>
      <xsd:element name="Domain" type="DomainType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="DomainType">
    <xsd:sequence>
      <xsd:element name="SubDomain"
        type="SubDomainType"
        minOccurs="0"
        maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="SubDomainType">
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>

</xsd:schema>

=== yoori/rtbserver_cobrazz/CMS/tests/CheckedResult/central-duplex-build/opt/oix/server/etc/moscow-test/adcluster/nnode1/DomainConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<cfg:DomainConfiguration xmlns:cfg="http://www.adintelligence.net/xsd/AdServer/Configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:colo="http://www.foros.com/cms/colocation" xsi:schemaLocation="http://www.adintelligence.net/xsd/AdServer/Configuration /opt/foros/server//xsd/CampaignSvcs/DomainConfig.xsd">
  <cfg:Domain name="ac">
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="edu"/>
    <cfg:SubDomain name="gov"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="mil"/>
    <cfg:SubDomain name="org"/>
  </cfg:Domain>
  <cfg:Domain name="ad">
    <cfg:SubDomain name="nom"/>
  </cfg:Domain>
  <cfg:Domain name="ae">
    <cfg:SubDomain name="co"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="org"/>
    <cfg:SubDomain name="sch"/>
    <cfg:SubDomain name="ac"/>
    <cfg:SubDomain name="gov"/>
    <cfg:SubDomain name="mil"/>
  </cfg:Domain>
  <cfg:Domain name="aero">
    <cfg:SubDomain name="accident-investigation"/>
    <cfg:SubDomain name="accident-prevention"/>
    <cfg:SubDomain name="aerobatic"/>
    <cfg:SubDomain name="aeroclub"/>
    <cfg:SubDomain name="aerodrome"/>
    <cfg:SubDomain name="agents"/>
    <cfg:SubDomain name="aircraft"/>
    <cfg:SubDomain name="airline"/>
    <cfg:SubDomain name="airport"/>
    <cfg:SubDomain name="air-surveillance"/>
    <cfg:SubDomain name="airtraffic"/>
    <cfg:SubDomain name="air-traffic-control"/>
    <cfg:SubDomain name="ambulance"/>
    <cfg:SubDomain name="amusement"/>
    <cfg:SubDomain name="association"/>
    <cfg:SubDomain name="author"/>
    <cfg:SubDomain name="ballooning"/>
    <cfg:SubDomain name="broker"/>
    <cfg:SubDomain name="caa"/>
    <cfg:SubDomain name="cargo"/>
    <cfg:SubDomain name="catering"/>
    <cfg:SubDomain name="certification"/>
    <cfg:SubDomain name="championship"/>
    <cfg:SubDomain name="charter"/>
    <cfg:SubDomain name="civilaviation"/>
    <cfg:SubDomain name="club"/>
    <cfg:SubDomain name="conference"/>
    <cfg:SubDomain name="consultant"/>
    <cfg:SubDomain name="consulting"/>
    <cfg:SubDomain name="control"/>
    <cfg:SubDomain name="council"/>
    <cfg:SubDomain name="crew"/>
    <cfg:SubDomain name="design"/>
    <cfg:SubDomain name="dgca"/>
    <cfg:SubDomain name="educator"/>
    <cfg:SubDomain name="emergency"/>
    <cfg:SubDomain name="engine"/>
    <cfg:SubDomain name="engineer"/>
    <cfg:SubDomain name="entertainment"/>
    <cfg:SubDomain name="equipment"/>
    <cfg:SubDomain name="exchange"/>
    <cfg:SubDomain name="express"/>
    <cfg:SubDomain name="federation"/>
    <cfg:SubDomain name="flight"/>
    <cfg:SubDomain name="freight"/>
    <cfg:SubDomain name="fuel"/>
    <cfg:SubDomain name="gliding"/>
    <cfg:SubDomain name="government"/>
    <cfg:SubDomain name="groundhandling"/>
    <cfg:SubDomain name="group"/>
    <cfg:SubDomain name="hanggliding"/>
    <cfg:SubDomain name="homebuilt"/>
    <cfg:SubDomain name="insurance"/>
    <cfg:SubDomain name="journal"/>
    <cfg:SubDomain name="journalist"/>
    <cfg:SubDomain name="leasing"/>
    <cfg:SubDomain name="logistics"/>
    <cfg:SubDomain name="magazine"/>
    <cfg:SubDomain name="maintenance"/>
    <cfg:SubDomain name="marketplace"/>
    <cfg:SubDomain name="media"/>
    <cfg:SubDomain name="microlight"/>
    <cfg:SubDomain name="modelling"/>
    <cfg:SubDomain name="navigation"/>
    <cfg:SubDomain name="parachuting"/>
    <cfg:SubDomain name="paragliding"/>
    <cfg:SubDomain name="passenger-association"/>
    <cfg:SubDomain name="pilot"/>
    <cfg:SubDomain name="press"/>
    <cfg:SubDomain name="production"/>
    <cfg:SubDomain name="recreation"/>
    <cfg:SubDomain name="repbody"/>
    <cfg:SubDomain name="res"/>
    <cfg:SubDomain name="research"/>
    <cfg:SubDomain name="rotorcraft"/>
    <cfg:SubDomain name="safety"/>
    <cfg:SubDomain name="scientist"/>
    <cfg:SubDomain name="services"/>
    <cfg:SubDomain name="show"/>
    <cfg:SubDomain name="skydiving"/>
    <cfg:SubDomain name="software"/>
    <cfg:SubDomain name="student"/>
    <cfg:SubDomain name="taxi"/>
    <cfg:SubDomain name="trader"/>
    <cfg:SubDomain name="trading"/>
    <cfg:SubDomain name="trainer"/>
    <cfg:SubDomain name="union"/>
    <cfg:SubDomain name="workinggroup"/>
    <cfg:SubDomain name="works"/>
  </cfg:Domain>
  <cfg:Domain name="af">
    <cfg:SubDomain name="gov"/>
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="org"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="edu"/>
  </cfg:Domain>
  <cfg:Domain name="ag">
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="org"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="co"/>
    <cfg:SubDomain name="nom"/>
  </cfg:Domain>
  <cfg:Domain name="ai">
    <cfg:SubDomain name="off"/>
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="org"/>
  </cfg:Domain>
  <cfg:Domain name="al">
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="edu"/>
    <cfg:SubDomain name="gov"/>
    <cfg:SubDomain name="mil"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="org"/>
  </cfg:Domain>
  <cfg:Domain name="am"/>
  <cfg:Domain name="an">
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="org"/>
    <cfg:SubDomain name="edu"/>
  </cfg:Domain>
  <cfg:Domain name="ao">
    <cfg:SubDomain name="ed"/>
    <cfg:SubDomain name="gv"/>
    <cfg:SubDomain name="og"/>
    <cfg:SubDomain name="co"/>
    <cfg:SubDomain name="pb"/>
    <cfg:SubDomain name="it"/>
  </cfg:Domain>
  <cfg:Domain name="aq"/>
  <cfg:Domain name="ar">
    <cfg:SubDomain name="congresodelalengua3"/>
    <cfg:SubDomain name="educ"/>
    <cfg:SubDomain name="gobiernoelectronico"/>
    <cfg:SubDomain name="mecon"/>
    <cfg:SubDomain name="nacion"/>
    <cfg:SubDomain name="nic"/>
    <cfg:SubDomain name="promocion"/>
    <cfg:SubDomain name="retina"/>
    <cfg:SubDomain name="uba"/>
    <cfg:SubDomain name="e164"/>
    <cfg:SubDomain name="in-addr"/>
    <cfg:SubDomain name="ip6"/>
    <cfg:SubDomain name="iris"/>
    <cfg:SubDomain name="uri"/>
    <cfg:SubDomain name="urn"/>
  </cfg:Domain>
  <cfg:Domain name="as">
    <cfg:SubDomain name="gov"/>
  </cfg:Domain>
  <cfg:Domain name="asia"/>
  <cfg:Domain name="at">
    <cfg:SubDomain name="ac"/>
    <cfg:SubDomain name="co"/>
    <cfg:SubDomain name="gv"/>
    <cfg:SubDomain name="or"/>
    <cfg:SubDomain name="biz"/>
    <cfg:SubDomain name="info"/>
    <cfg:SubDomain name="priv"/>
  </cfg:Domain>
  <cfg:Domain name="au">
    <cfg:SubDomain name="act.edu"/>
    <cfg:SubDomain name="nsw.edu"/>
    <cfg:SubDomain name="nt.edu"/>
    <cfg:SubDomain name="qld.edu"/>
    <cfg:SubDomain name="sa.edu"/>
    <cfg:SubDomain name="tas.edu"/>
    <cfg:SubDomain name="vic.edu"/>
    <cfg:SubDomain name="wa.edu"/>
    <cfg:SubDomain name="act.gov"/>
    <cfg:SubDomain name="nt.gov"/>
    <cfg:SubDomain name="qld.gov"/>
    <cfg:SubDomain name="sa.gov"/>
    <cfg:SubDomain name="tas.gov"/>
    <cfg:SubDomain name="vic.gov"/>
    <cfg:SubDomain name="wa.gov"/>
    <cfg:SubDomain name="act"/>
    <cfg:SubDomain name="nsw"/>
    <cfg:SubDomain name="nt"/>
    <cfg:SubDomain name="qld"/>
    <cfg:SubDomain name="sa"/>
    <cfg:SubDomain name="tas"/>
    <cfg:SubDomain name="vic"/>
    <cfg:SubDomain name="wa"/>
  </cfg:Domain>
  <cfg:Domain name="aw">
    <cfg:SubDomain name="com"/>
  </cfg:Domain>
  <cfg:Domain name="ax"/>
  <cfg:Domain name="az">
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="int"/>
    <cfg:SubDomain name="gov"/>
    <cfg:SubDomain name="org"/>
    <cfg:SubDomain name="edu"/>
    <cfg:SubDomain name="info"/>
    <cfg:SubDomain name="pp"/>
    <cfg:SubDomain name="mil"/>
    <cfg:SubDomain name="name"/>
    <cfg:SubDomain name="pro"/>
    <cfg:SubDomain name="biz"/>
  </cfg:Domain>
  <cfg:Domain name="ba">
    <cfg:SubDomain name="org"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="edu"/>
    <cfg:SubDomain name="gov"/>
    <cfg:SubDomain name="mil"/>
    <cfg:SubDomain name="unsa"/>
    <cfg:SubDomain name="unbi"/>
    <cfg:SubDomain name="co"/>
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="rs"/>
  </cfg:Domain>
  <cfg:Domain name="bb">
    <cfg:SubDomain name="biz"/>
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="edu"/>
    <cfg:SubDomain name="gov"/>
    <cfg:SubDomain name="info"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="org"/>
    <cfg:SubDomain name="store"/>
  </cfg:Domain>
  <cfg:Domain name="bd"/>
  <cfg:Domain name="be">
    <cfg:SubDomain name="ac"/>
  </cfg:Domain>
  <cfg:Domain name="bf">
    <cfg:SubDomain name="gov"/>
  </cfg:Domain>
  <cfg:Domain name="bg">
    <cfg:SubDomain name="a"/>
    <cfg:SubDomain name="b"/>
    <cfg:SubDomain name="c"/>
    <cfg:SubDomain name="d"/>
    <cfg:SubDomain name="e"/>
    <cfg:SubDomain name="f"/>
    <cfg:SubDomain name="g"/>
    <cfg:SubDomain name="h"/>
    <cfg:SubDomain name="i"/>
    <cfg:SubDomain name="j"/>
    <cfg:SubDomain name="k"/>
    <cfg:SubDomain name="l"/>
    <cfg:SubDomain name="m"/>
    <cfg:SubDomain name="n"/>
    <cfg:SubDomain name="o"/>
    <cfg:SubDomain name="p"/>
    <cfg:SubDomain name="q"/>
    <cfg:SubDomain name="r"/>
    <cfg:SubDomain name="s"/>
    <cfg:SubDomain name="t"/>
    <cfg:SubDomain name="u"/>
    <cfg:SubDomain name="v"/>
    <cfg:SubDomain name="w"/>
    <cfg:SubDomain name="x"/>
    <cfg:SubDomain name="y"/>
    <cfg:SubDomain name="z"/>
    <cfg:SubDomain name="0"/>
    <cfg:SubDomain name="1"/>
    <cfg:SubDomain name="2"/>
    <cfg:SubDomain name="3"/>
    <cfg:SubDomain name="4"/>
    <cfg:SubDomain name="5"/>
    <cfg:SubDomain name="6"/>
    <cfg:SubDomain name="7"/>
    <cfg:SubDomain name="8"/>
    <cfg:SubDomain name="9"/>
  </cfg:Domain>
  <cfg:Domain name="bh">
    <cfg:SubDomain name="com"/>
    <cfg:SubDomain name="edu"/>
    <cfg:SubDomain name="net"/>
    <cfg:SubDomain name="org"/>
