=== yoori/rtbserver_cobrazz/xsd/Utils/CTRGeneratorConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.adintelligence.net/xsd/AdServer/Configuration"
  xmlns="http://www.adintelligence.net/xsd/AdServer/Configuration"
  elementFormDefault="qualified"
  xml:lang="en"
  version="1.0">

  <xsd:annotation>
    <xsd:documentation>
      CTRGenerator Configuration File XML Schema
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="CTRGenerator" type="CTRGeneratorType"/>

  <xsd:complexType name="CTRGeneratorType">
    <xsd:sequence>
      <xsd:element name="Model" type="ModelType" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ModelType">
    <xsd:sequence>
      <xsd:element name="Feature" type="FeatureType" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="features_dimension" type="xsd:positiveInteger" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="FeatureType">
    <xsd:sequence>
      <xsd:element name="BasicFeature" type="BasicFeatureType"
        minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="BasicFeatureType">
    <xsd:attribute name="name" type="xsd:string" use="required"/>
  </xsd:complexType>
</xsd:schema>

=== yoori/rtbserver_cobrazz/Predictor/Scripts/CTRConfigTempl/UncorrelateConf.xml
<?xml version="1.0" encoding="utf-8"?>
<cfg:CTRGenerator xmlns:cfg="http://www.adintelligence.net/xsd/AdServer/Configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:colo="http://www.foros.com/cms/colocation"
  xsi:schemaLocation="http://www.adintelligence.net/xsd/AdServer/Configuration /opt/foros/server/xsd/Utils/CTRGeneratorConfig.xsd">
  <cfg:Model features_dimension="24">

  <cfg:Feature>
    <cfg:BasicFeature name="publisher"/>
  </cfg:Feature>

  <cfg:Feature>
    <cfg:BasicFeature name="tag"/>
  </cfg:Feature>

  <cfg:Feature>
    <cfg:BasicFeature name="sizeid"/>
  </cfg:Feature>

  <cfg:Feature>
    <cfg:BasicFeature name="wd"/>
  </cfg:Feature>

  <cfg:Feature>
    <cfg:BasicFeature name="hour"/>
  </cfg:Feature>

  <cfg:Feature>
    <cfg:BasicFeature name="device"/>
  </cfg:Feature>

  <cfg:Feature>
    <cfg:BasicFeature name="campaign"/>
  </cfg:Feature>

  <cfg:Feature>
    <cfg:BasicFeature name="group"/>
  </cfg:Feature>

  <cfg:Feature>
    <cfg:BasicFeature name="ccid"/>
  </cfg:Feature>

  <!--
  <cfg:Feature>
    <cfg:BasicFeature name="campaign_freq"/>
  </cfg:Feature>
  -->

  <cfg:Feature>
    <cfg:BasicFeature name="campaign_freq_log"/>
  </cfg:Feature>

  <cfg:Feature>
    <cfg:BasicFeature name="geoch"/>      
  </cfg:Feature>

  </cfg:Model>

</cfg:CTRGenerator>
